import { StyleSheet } from 'react-native';
import { colors, shadow, spacing } from '../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  shell: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: colors.background,
  },
  shellCompact: {
    flexDirection: 'column',
  },
  sidebar: {
    width: 228,
    backgroundColor: '#050B13',
    borderRightWidth: 1,
    borderRightColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
  },
  sidebarWide: {
    width: 280,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
  },
  sidebarUltraWide: {
    width: 320,
  },
  sidebarCompact: {
    display: 'none',
  },
  sidebarBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  brandMark: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(35, 136, 255, 0.08)',
    marginRight: spacing.sm,
  },
  brandTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  brandSubtitle: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.8,
    marginTop: spacing.xxs,
  },
  navList: {
    gap: spacing.xs,
  },
  navItem: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
  },
  navItemActive: {
    backgroundColor: 'rgba(35, 136, 255, 0.12)',
    borderColor: 'rgba(35, 136, 255, 0.36)',
  },
  navText: {
    color: colors.muted,
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    marginLeft: spacing.sm,
  },
  navTextActive: {
    color: colors.primary,
  },
  navBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.secondary,
  },
  navBadgeText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '900',
  },
  content: {
    flexGrow: 1,
    padding: spacing.lg,
    paddingBottom: spacing.xl,
    maxWidth: 1220,
    width: '100%',
  },
  contentWide: {
    maxWidth: 1920,
    padding: spacing.xl,
  },
  contentUltraWide: {
    maxWidth: 3200,
    padding: spacing.xxl,
  },
  contentCompact: {
    padding: spacing.md,
  },
  banner: {
    minHeight: 338,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    ...shadow,
  },
  bannerWide: {
    minHeight: 460,
  },
  bannerUltraWide: {
    minHeight: 620,
  },
  bannerCompact: {
    minHeight: 300,
  },
  bannerImage: {
    borderRadius: 8,
  },
  bannerOverlay: {
    flex: 1,
    justifyContent: 'center',
    padding: spacing.xl,
    backgroundColor: 'rgba(2, 6, 14, 0.44)',
  },
  bannerOverlayWide: {
    padding: spacing.xxl,
  },
  bannerOverlayCompact: {
    padding: spacing.lg,
  },
  bannerKicker: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.8,
    marginBottom: spacing.sm,
  },
  bannerTitle: {
    color: colors.text,
    maxWidth: 620,
    fontSize: 40,
    fontWeight: '900',
    lineHeight: 46,
    textTransform: 'uppercase',
  },
  bannerTitleWide: {
    maxWidth: 860,
    fontSize: 56,
    lineHeight: 64,
  },
  bannerTitleUltraWide: {
    maxWidth: 1120,
    fontSize: 72,
    lineHeight: 82,
  },
  bannerTitleCompact: {
    fontSize: 28,
    lineHeight: 34,
  },
  bannerText: {
    color: '#DCE7F6',
    maxWidth: 520,
    fontSize: 15,
    lineHeight: 22,
    marginTop: spacing.md,
  },
  bannerTextWide: {
    maxWidth: 720,
    fontSize: 18,
    lineHeight: 28,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.md,
  },
  metricsRowCompact: {
    flexDirection: 'column',
  },
  orbitalSection: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  orbitalSectionCompact: {
    flexDirection: 'column',
  },
  mapCard: {
    flex: 2,
    minHeight: 430,
    backgroundColor: colors.card,
    borderRadius: 8,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  mapCardWide: {
    minHeight: 560,
    padding: spacing.xl,
  },
  mapCardUltraWide: {
    minHeight: 740,
    padding: spacing.xxl,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.md,
  },
  liveBadge: {
    color: colors.success,
    borderWidth: 1,
    borderColor: 'rgba(52, 199, 89, 0.45)',
    borderRadius: 4,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1,
  },
  orbitalMap: {
    flex: 1,
    minHeight: 310,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  orbitalMapWide: {
    minHeight: 440,
  },
  orbitalMapUltraWide: {
    minHeight: 600,
  },
  orbitLine: {
    position: 'absolute',
    width: '92%',
    height: '42%',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(147, 164, 188, 0.2)',
  },
  orbitLineOne: {
    transform: [{ rotate: '-16deg' }],
  },
  orbitLineTwo: {
    width: '78%',
    height: '34%',
    borderColor: 'rgba(35, 136, 255, 0.24)',
    transform: [{ rotate: '19deg' }],
  },
  orbitLineThree: {
    width: '62%',
    height: '29%',
    borderColor: 'rgba(255, 149, 0, 0.2)',
    transform: [{ rotate: '42deg' }],
  },
  globe: {
    width: 176,
    height: 176,
    borderRadius: 88,
    borderWidth: 1,
    borderColor: 'rgba(130, 190, 255, 0.8)',
    backgroundColor: '#103D66',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.48,
    shadowRadius: 24,
    elevation: 8,
    overflow: 'hidden',
  },
  globeWide: {
    width: 240,
    height: 240,
    borderRadius: 120,
  },
  globeUltraWide: {
    width: 340,
    height: 340,
    borderRadius: 170,
  },
  globeGlow: {
    position: 'absolute',
    width: 112,
    height: 112,
    borderRadius: 56,
    right: -10,
    top: 18,
    backgroundColor: 'rgba(44, 148, 255, 0.42)',
  },
  globeGlowWide: {
    width: 154,
    height: 154,
    borderRadius: 77,
    right: -12,
    top: 24,
  },
  globeGlowUltraWide: {
    width: 220,
    height: 220,
    borderRadius: 110,
    right: -20,
    top: 36,
  },
  globeMeridian: {
    position: 'absolute',
    width: 82,
    height: 176,
    borderRadius: 80,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.16)',
  },
  globeMeridianWide: {
    width: 112,
    height: 240,
    borderRadius: 112,
  },
  globeMeridianUltraWide: {
    width: 160,
    height: 340,
    borderRadius: 160,
  },
  globeMeridianTilt: {
    transform: [{ rotate: '34deg' }],
  },
  globeEquator: {
    position: 'absolute',
    width: 176,
    height: 74,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
  },
  globeEquatorWide: {
    width: 240,
    height: 102,
    borderRadius: 90,
  },
  globeEquatorUltraWide: {
    width: 340,
    height: 144,
    borderRadius: 126,
  },
  debrisPoint: {
    position: 'absolute',
    width: 7,
    height: 7,
    borderRadius: 4,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
  },
  debrisPointLarge: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: spacing.sm,
  },
  legendText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  cardLarge: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: 8,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
  },
  cardLargeWide: {
    padding: spacing.xl,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  sectionValue: {
    color: colors.primary,
    fontSize: 26,
    fontWeight: '900',
    marginTop: spacing.sm,
  },
  sectionDescription: {
    color: colors.muted,
    marginTop: spacing.sm,
    fontSize: 14,
    lineHeight: 20,
  },
  buttonRow: {
    flexDirection: 'row',
    marginTop: spacing.lg,
  },
  actionButton: {
    backgroundColor: colors.primary,
    borderRadius: 6,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    marginRight: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#4EA1FF',
  },
  actionButtonSecondary: {
    backgroundColor: 'rgba(7, 17, 31, 0.82)',
    borderColor: 'rgba(255, 255, 255, 0.32)',
  },
  actionText: {
    color: colors.text,
    marginLeft: spacing.xs,
    fontWeight: '800',
  },
  statusCard: {
    marginTop: spacing.lg,
    backgroundColor: colors.card,
    borderRadius: 8,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    paddingVertical: spacing.sm,
  },
  statusLabel: {
    color: colors.text,
    fontWeight: '700',
  },
  statusValue: {
    color: colors.primary,
    fontWeight: '800',
  },
  alertCard: {
    marginTop: spacing.lg,
    backgroundColor: colors.card,
    borderRadius: 8,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  alertRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    paddingVertical: spacing.sm,
  },
  alertName: {
    color: colors.text,
    fontWeight: '700',
  },
  alertBadge: {
    color: colors.warning,
    fontWeight: '800',
  },
  linkButton: {
    marginTop: spacing.lg,
    alignItems: 'center',
  },
  linkText: {
    color: colors.primary,
    fontWeight: '800',
  },
  footer: {
    marginTop: spacing.xl,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
  },
  footerBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerLogo: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    marginLeft: spacing.xs,
  },
  footerLinks: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.md,
  },
  footerLink: {
    color: colors.primary,
    fontWeight: '800',
  },
  copyright: {
    color: colors.muted,
    textAlign: 'center',
    marginTop: spacing.md,
    fontSize: 12,
  },
});
